site_name: Chicago Booth ML
site_author: Robert E. McCulloch, Mladen Kolar

include_nav: True
include_next_prev: False
pages:
  - <i class="fa fa-home"></i>: 'index.md'
  - Syllabus & Lectures:
    - Syllabus: 'Syllabus.md'
    - Lecture 01: 'Lectures/Lecture Week 01.md'
    - Lecture 02: 'Lectures/Lecture Week 02.md'
    - Lecture 03: 'Lectures/Lecture Week 03.md'
    - Lecture 04: 'Lectures/Lecture Week 04.md'
    - Lecture 05: 'Lectures/Lecture Week 05.md'
    - Lecture 06: 'Lectures/Lecture Week 06.md'
    - Lecture 07: 'Lectures/Lecture Week 07.md'
    - Lecture 08: 'Lectures/Lecture Week 08.md'
    - Lecture 09: 'Lectures/Lecture Week 09.md'
    - Lecture 10: 'Lectures/Lecture Week 10.md'
  - Installation:
    - Computer Operating System Requirements: 'Installation/Computer Operating System Requirements.md'
    - Cygwin (for Windows users only): 'Installation/Cygwin.md'
    - Git, GitHub & SourceTree: 'Installation/Git, GitHub & SourceTree.md'
    - R, RStudio & CRAN Packages: 'Installation/R, RStudio & CRAN Packages.md'
    - Python Anaconda, PyCharm IDE, and Conda & PyPI Packages: 'Installation/Python Anaconda, PyCharm IDE, and Conda & PyPI Packages.md'
    - Python Theano package: 'Installation/Python Theano.md'
  - Tutorials:
    - R - R Markdown: 'Tutorials/R Markdown Tutorial.md'
    - R - data.table: 'Tutorials/R data.table Tutorial.md'
  - Links: 'Links.md'

repo_url: 'http://github.com/ChicagoBoothML/MachineLearning_Fall2015'

theme: mkdocs
extra_css: ['https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css',
            'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css',
            'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css',
            'styles.css']

# math extension
# ref: https://github.com/mkdocs/mkdocs/issues/253
markdown_extensions: [math]
extra_javascript: ['https://code.jquery.com/jquery-2.1.3.min.js',
                   # 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js',   # disabling this because it causes problems to the drop-downs
                   'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML',
                   'mathjaxhelper.js']
